### ISSUE TITLE
jpasskittest.p12 cert expired?

### ISSUE THREAD

**Issue by passif** [drallgood/jpasskit#103]
Hi

New to jpasskit (and it looks awesome). When running the tests I get failures on some of the test related to the signing of the pass.  According to the TestNG reports it is because the cert has expired.  The detail are as follows:
`testFileBasedSigningWithGeneratedPass
java.security.cert.CertificateExpiredException: NotAfter: Mon Jan 22 21:57:49 CAT 2018
	at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:629)
	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:602)
	at de.brendamour.jpasskit.signing.PKSigningInformationUtil.checkCertsAndReturnSigningInformationObject(PKSigningInformationUtil.java:255)
... Removed 31 stack frames`

There are a total of 15 failing tests.

**Comment by drallgood** [comment]
Thanks for catching this one. I'll update the certificate tomorrow morning when I'm at my desk.

**Comment by drallgood** [comment]
Fixed.

Thanks for reporting this!
