### ISSUE TITLE
[ Signing Pass ] Could not initialize class org.bouncycastle.cms.CMSSignedDataGenerator

### ISSUE THREAD

**Issue by BESAFX** [drallgood/jpasskit#195]
Hi @drallgood 

Thanks for quick response for last issue, after i deployed latest snapshot as you mention me [Here](https://github.com/drallgood/jpasskit/issues/192), i found another one related to signing passes after sharing and publishing it, and here is a logs: 
`2019-06-18 05:10:12,274 ERROR [3ddfd4b0-482a-4368-b0bc-127c1686d2cf] - io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request:
 d06c961df7f8e79d
  ! java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.cms.CMSSignedDataGenerator
! at de.brendamour.jpasskit.signing.PKAbstractSigningUtil.signManifestUsingContent(PKAbstractSigningUtil.java:90)
! at de.brendamour.jpasskit.signing.PKAbstractSigningUtil.signManifestFile(PKAbstractSigningUtil.java:82)
! at de.brendamour.jpasskit.signing.PKInMemorySigningUtil.createSignedAndZippedPersonalizedPkPassArchive(PKInMemorySigningUtil.java:103)
! at com.waterfall.wallet.pass.signing.service.impl.PassSigningServiceImpl.assembleAndSignPass(PassSigningServiceImpl.java:515)
! at com.waterfall.wallet.pass.signing.service.impl.PassSigningServiceImpl.createPassWithConfig(PassSigningServiceImpl.java:713)
! at com.waterfall.wallet.pass.signing.service.impl.PassSigningServiceImpl.createOrUpdatePass(PassSigningServiceImpl.java:663)
! at com.waterfall.wallet.pass.signing.rest.SigningAPI.signPass(SigningAPI.java:167)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvide
r.java:160)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)`

Please notice that i used version: `0.2.0-SNAPSHOT`

Thanks :)

**Comment by BESAFX** [comment]
@drallgood 
I found the solution for this issue, where i am using Passkit library with JavaAPN and both used different types of same library of (bouncycastle library), 
Passkit used bouncycastle version 1.62
JavaAPN used bouncycastle version 1.54

so i changed order in my pom to install latest one 

Thanks @drallgood
