### ISSUE TITLE
raw folder does not exist

### ISSUE THREAD

**Issue by isc-yzheng** [drallgood/jpasskit#307]
Hi,
I faced an issue when trying to run the sample code provided in your tutorial.txt file.
I create a folder in the main.resource folder and change the path in the code. 
It always shows "(the file name) does not exist
This is the full error msg:

_**SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
de.brendamour.jpasskit.signing.PKSigningException: Error when provisioning template
	at de.brendamour.jpasskit.signing.PKFileBasedSigningUtil.createSignedAndZippedPersonalizedPkPassArchive(PKFileBasedSigningUtil.java:87)
	at de.brendamour.jpasskit.signing.PKFileBasedSigningUtil.createSignedAndZippedPkPassArchive(PKFileBasedSigningUtil.java:76)
	at de.brendamour.jpasskit.signing.PKFileBasedSigningUtil.createSignedAndZippedPkPassArchive(PKFileBasedSigningUtil.java:120)
	at de.brendamour.jpasskit.signing.PKSigningUtil.createSignedAndZippedPkPassArchive(PKSigningUtil.java:44)
	at testPassKit.CreatPass.main(CreatPass.java:69)
Caused by: java.io.FileNotFoundException: Source './testing' does not exist
	at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1383)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1346)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1246)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1215)
	at de.brendamour.jpasskit.signing.PKPassTemplateFolder.provisionPassAtDirectory(PKPassTemplateFolder.java:51)
	at de.brendamour.jpasskit.signing.PKFileBasedSigningUtil.createSignedAndZippedPersonalizedPkPassArchive(PKFileBasedSigningUtil.java:85)
	... 4 more
failed!**_

Could you please help me out with this? Thank you!

**Comment by drallgood** [comment]
Probably means the path to your folder is not correct. Please make sure to specify it correctly.
It will depend on your deployment/environment how that is done.

**Comment by isc-yzheng** [comment]
Hi, thx for replying. I put the folder in the main/resource, together with those certificate. And it doesn't complaint about the path for certs, so I'm a bit confused. I try to name it differently for a few times, all failed.    (ps: that was just an empty folder, do I need to put some files inside?)

**Comment by isc-yzheng** [comment]
> Probably means the path to your folder is not correct. Please make sure to specify it correctly.
> It will depend on your deployment/environment how that is done.

I tried to put the folder in both main/java and main/resource. Both failed. The way I specified the path is just "./<foldername>"

**Comment by isc-yzheng** [comment]
I also find an error with the line 162 saying "The method newFileSystem(Path, ClassLoader) is ambiguous for the type FileSystems"  in src/test/java/de.brendamour.jpasskit.signing/PKFileBasedSigningUtilTest.java

does this error have anything to do with the error I faced with the path to folder?

**Comment by JannikArndt** [comment]
Make sure the `path` doesn't contain a `file://` prefix. For me, 

```scala
val templateFolder = getClass.getClassLoader.getResource("template").getPath
```
 worked (note: it's Scala, but Java will be similar)
